### ISSUE TITLE
System.DLLNotFoundException on Linux

### ISSUE THREAD

**Issue by foxnne** [prime31/V-C-Wrapper-Generator#1]
@prime31 Hopefully I haven't messed this all up on my end.

OS: Kubuntu 19.10
- clang -v : clang version 9.0.0-2 (tags/RELEASE_900/final)
- dotnet core 3.0 installed

I just pulled the latest Odin branch and built using ```dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true```

Generated json and matched the example FNA3D config.

Running ./VGenerator -g fna.json outputs the following:

> Unhandled` exception. System.DllNotFoundException: Unable to load shared library 'libclang' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibclang: cannot open shared object file: No such file or directory

>  at ClangSharp.clang.createIndex(Int32 excludeDeclarationsFromPCH, Int32 displayDiagnostics)

> at ClangSharp.CXIndex.Create(Boolean excludeDeclarationsFromPch, Boolean displayDiagnostics)

> at CppAst.CppParser.ParseInternal(List`1 cppFiles, CppParserOptions options)

> at CppAst.CppParser.ParseFiles(List`1 cppFilenameList, CppParserOptions options)

> at Generator.Program.Run(Config config)

> at Generator.Program.Main(String[] args)

> Aborted (core dumped)`

**Comment by prime31** [comment]
Sounds like a missing libclang.so. Make sure you run dotnet restore so that NuGet can download the NuGet packages, though it shouldn’t even be able to compile without them. Did you try running directly in VS Code to see if it provides some more info? It will also prompt you to do the restore automatically with the C# extension installed.

**Comment by foxnne** [comment]
I had thought so as well, but ```dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true``` reports a successful restore before building, and in the /src/bin/Release/netcoreapp3.0/linux-x64/ folder I see libclang.so there. 

It seems strange that in the output it shows "liblibclang" not being found.

**Comment by prime31** [comment]
That could be it. Try it without single file export and see if renaming clang fixes it. Libs should always be just “lib” + name

**Comment by foxnne** [comment]
Okay I tried that as well as installed VSCode and ran the build task. Both have the same outcome. libclang.so is in both builds and renaming that seems to have no effect. Debugging in VSCode shows this is coming from CppAst.dll.

This should be a easily reproducible issue, I'm basically on a fresh install of ubuntu 19.10. Just pulled this, installed dotnet core 3.0, checked that clang was installed and built.

**Comment by prime31** [comment]
You’ll probably want to report that upstream at the Clang# repo. I don’t have a clue how Clang# handles dependencies per platform. I just happened to use the Clang# NuGet package for parsing C.

**Comment by foxnne** [comment]
Alright thanks prime, It works perfectly fine on Win10, so no worries, I'll just generate there.
